global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - "/etc/prometheus/alerting_rules/*.yaml"
  - "/etc/prometheus/alerting_rules/*.yml"
  - "/etc/prometheus/extra/alerting_rules/*.yml"
  - "/etc/prometheus/extra/alerting_rules/*.yaml"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ["localhost:9093"]

scrape_configs:
  - job_name: "plc_exporter"
    metrics_path: "/"
    scheme: "http"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9075"]
